version: 2.1

jobs:
  build:
    docker:
      - image: circleci/dart:2.13.0

    steps:
      - checkout

      - run:
          name: Install Flutter
          command: |
            sudo apt-get install -y lib32stdc++6
            curl https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_2.5.3-stable.tar.xz -o flutter.tar.xz
            tar xf flutter.tar.xz
            export PATH="$PATH:`pwd`/flutter/bin"
            flutter precache
            flutter doctor -v

      - run:
          name: Get dependencies
          command: flutter pub get

      - run:
          name: Build the app
          command: flutter build apk --release

      - store_artifacts:
          path: build/web/index.html

  deploy_to_firebase:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      - run:
          name: Install Firebase CLI
          command: curl -sL https://firebase.tools | bash

      - run:
          name: Authenticate Firebase
          command: firebase login:ci --no-localhost --interactive

      - run:
          name: Deploy to Firebase
          command: firebase deploy --only hosting --token $FIREBASE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_to_firebase:
          requires:
            - build
